version: '3.4'

services:
  #Keeps containers up to date - https://containrrr.github.io/watchtower/
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
      
  gvm:
    image: isaudits/gvm
    hostname: gvm
    container_name: gvm
    ports:
      - "443:9392"
    env_file:
      - ./config/local.env
    volumes:
      - ./data/config:/config
      - ./data/gvm/var/lib:/usr/local/var/lib
      #- ./data/database:/var/lib/postgresql/data
      - database:/var/lib/postgresql/data
      - plugins:/usr/local/var/lib/openvas/plugins
      - cert-data:/usr/local/var/lib/gvm/cert-data
      - scap-data:/usr/local/var/lib/gvm/scap-data
      
    tty: true

volumes:
  database: {}
  plugins: {}
  cert-data: {}
  scap-data: {}