version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
    hostname: portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    
openvas:
    image: charlieit/gvm:openvas-21.4
    hostname: openvas
    container_name: openvas
    ports:
      - "9391:9391"
    env_file:
      - ./config/local.env
    volumes:
      - ./config:/config
      - gvm_data:/usr/local/var/lib


volumes:
  volumes:
  portainer:{}
  gvm_data:
    name: gvm_data
