#!/bin/bash
set -ueo pipefail

#docker push charlieit/gvm:build-21.4
#docker push charlieit/gvm:base-21.4
#docker push charlieit/gvm:openvas-21.4
#docker push charlieit/gvm:gvmd-21.4
#docker push charlieit/gvm:gvm-21.4
#docker push charlieit/gvm:dev

docker push charlieit/gvm
